version: '3.1'

services:

  postgres:
    image: postgres:12 
    environment:
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5342:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  data:
