# Generated by Django 5.0.6 on 2024-06-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='esrb_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='playtime',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='suggestions_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='website',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('popular', 'Popular'), ('recent', 'Lançamento Recente'), ('top_rated', 'Melhor Avaliado')], default='popular', max_length=10),
        ),
    ]
